[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 921600
board_build.flash_mode = qio
board_build.f_cpu = 240000000L
lib_deps = 
    adafruit/Adafruit AMG88xx @ ^1.0.5
    sparkfun/SparkFun MLX90640 Library @ ^1.0.3
build_flags = 
    -D MLX90640_I2C_ADDR=0x33
    -D AMG_ADDR=0x69